# Generated by Django 4.1.2 on 2022-12-03 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSites",
            fields=[
                (
                    "site_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner",
                    models.EmailField(help_text="Managed by user", max_length=254),
                ),
                ("domain", models.URLField(help_text="Site URl where to index")),
                (
                    "alias",
                    models.CharField(
                        help_text="Alias for your site url. Max 1000 chars allowed",
                        max_length=1000,
                    ),
                ),
                (
                    "contact",
                    models.EmailField(
                        help_text="For Contact Purposes. Enter a valid email",
                        max_length=254,
                    ),
                ),
                (
                    "links_limit",
                    models.IntegerField(
                        default=1,
                        help_text="Max number of links to index. MAX 1000 allowed.",
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("links_fetched", models.IntegerField(default=1)),
                ("last_crawled", models.DateTimeField(auto_now_add=True)),
                ("crawler_status", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("owner", "domain")},
            },
        ),
        migrations.CreateModel(
            name="SiteLinks",
            fields=[
                (
                    "link_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("title", models.TextField(blank=True)),
                ("response_code", models.CharField(default="NA", max_length=10)),
                (
                    "site_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.usersites",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteIndexer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200)),
                ("site_id", models.UUIDField()),
                ("link_id", models.UUIDField()),
                ("score", models.FloatField()),
            ],
            options={
                "unique_together": {("site_id", "word")},
            },
        ),
    ]
