# Generated by Django 4.1.2 on 2022-12-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="siteindexer",
            unique_together={("site_id", "word", "link_id")},
        ),
    ]
